SELECT TOP (1000) [Id]
      ,[FirstName]
      ,[LastName]
      ,[Email]
      ,[StudentId]
      ,[Role]
      ,[PasswordHash]
      ,[IsActive]
      ,[CreatedAt]
      ,[UpdatedAt]
      ,[IsEmailVerified]
      ,[OtpCode]
      ,[OtpExpiresAt]
  FROM [DocTrackerDB].[dbo].[Users]